services:
  - type: web
    name: tech-oidashi-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  - type: web
    name: tech-oidashi-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build