services:
  - type: static
    name: tech-oidashi-client
    buildCommand: cd client && npm install && npm run build
    publishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tech-oidashi-server.onrender.com